controller_list:
  - name: fake_excavator_arm_controller
    type: $(arg execution_type)
    joints:
      - waist
      - shoulder
      - elbow
  - name: fake_excavator_eef_controller
    type: $(arg execution_type)
    joints:
      - wrist
  - name: fake_excavator_chain_controller
    type: $(arg execution_type)
    joints:
      - waist
      - shoulder
      - elbow
      - wrist
initial:  # Define initial robot poses.
  - group: excavator_chain
    pose: home